# Generated by Django 6.1 on 2026-09-04 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('knowledge_base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The common name of the symptom (e.g., Fever, Chest Pain).', max_length=150, unique=True, verbose_name='Symptom Name')),
                ('description', models.TextField(blank=True, help_text='Optional clinical description for admin reference.', verbose_name='Description')),
                ('is_red_flag', models.BooleanField(default=False, help_text='Check if this symptom requires immediate emergency attention.', verbose_name='Red Flag / Emergency Symptom')),
                ('emergency_message', models.TextField(blank=True, help_text='The warning message displayed to the user if this red-flag symptom is selected.', verbose_name='Emergency Warning Message')),
            ],
            options={
                'verbose_name': 'Symptom',
                'verbose_name_plural': 'Symptoms',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the medical condition.', max_length=150, unique=True, verbose_name='Condition Name')),
                ('description', models.TextField(blank=True, help_text='A general description of the condition.', verbose_name='Description')),
                ('articles', models.ManyToManyField(blank=True, help_text='Select articles that provide information about this condition.', related_name='related_conditions', to='knowledge_base.article', verbose_name='Related Knowledge Base Articles')),
            ],
            options={
                'verbose_name': 'Condition',
                'verbose_name_plural': 'Conditions',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ConditionSymptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.PositiveIntegerField(default=1, help_text='Higher weight means this symptom is a stronger indicator of the condition. Tunable from admin.', verbose_name='Weight (Importance)')),
                ('is_core', models.BooleanField(default=False, help_text='Check if this is a primary/defining symptom of the condition.', verbose_name='Core Symptom')),
                ('notes', models.TextField(blank=True, help_text='Optional notes for administrators about this rule.', verbose_name='Admin Notes')),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symptom_rules', to='medical_data.condition', verbose_name='Condition')),
                ('symptom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condition_rules', to='medical_data.symptom', verbose_name='Symptom')),
            ],
            options={
                'verbose_name': 'Condition-Symptom Rule',
                'verbose_name_plural': 'Condition-Symptom Rules',
                'ordering': ['condition', '-weight', 'symptom'],
                'constraints': [models.UniqueConstraint(fields=('condition', 'symptom'), name='unique_condition_symptom_rule')],
            },
        ),
    ]
