# Generated by Django 6.1 on 2026-09-04 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medical_data', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthEpisode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='A brief description of this health issue (e.g., "Flu-like symptoms", "Knee pain")', max_length=255, verbose_name='Episode Title')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('MATCHING', 'Matching Symptoms'), ('AWAITING_DOCTOR', 'Awaiting Doctor'), ('IN_CONSULTATION', 'In Consultation'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('EMERGENCY', 'Emergency')], default='OPEN', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('client', models.ForeignKey(limit_choices_to={'role': 'CLIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='health_episodes', to=settings.AUTH_USER_MODEL, verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Health Episode',
                'verbose_name_plural': 'Health Episodes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EpisodeSymptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reported_severity', models.CharField(choices=[('MILD', 'Mild'), ('MODERATE', 'Moderate'), ('SEVERE', 'Severe')], default='MODERATE', max_length=10, verbose_name='Reported Severity')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Added At')),
                ('symptom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episode_occurrences', to='medical_data.symptom', verbose_name='Symptom')),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episode_symptoms', to='episodes.healthepisode', verbose_name='Health Episode')),
            ],
            options={
                'verbose_name': 'Episode Symptom',
                'verbose_name_plural': 'Episode Symptoms',
                'ordering': ['added_at'],
                'constraints': [models.UniqueConstraint(fields=('episode', 'symptom'), name='unique_episode_symptom')],
            },
        ),
        migrations.CreateModel(
            name='EpisodeConditionMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_score', models.PositiveIntegerField(default=0, help_text='Total weight of matched symptoms for this condition', verbose_name='Match Score')),
                ('coverage_percentage', models.FloatField(default=0.0, help_text='Percentage of the condition total symptoms that were matched', verbose_name='Coverage Percentage')),
                ('matched_at', models.DateTimeField(auto_now_add=True, verbose_name='Matched At')),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episode_matches', to='medical_data.condition', verbose_name='Condition')),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condition_matches', to='episodes.healthepisode', verbose_name='Health Episode')),
            ],
            options={
                'verbose_name': 'Episode Condition Match',
                'verbose_name_plural': 'Episode Condition Matches',
                'ordering': ['-match_score', '-coverage_percentage'],
                'constraints': [models.UniqueConstraint(fields=('episode', 'condition'), name='unique_episode_condition_match')],
            },
        ),
    ]
