# Generated by Django 6.1 on 2026-09-05 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
        ('episodes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(help_text='Explain why you need a doctor consultation for this episode', verbose_name='Reason for Request')),
                ('doctor_notes', models.TextField(blank=True, help_text='Notes from the doctor (visible to client)', verbose_name='Doctor Notes')),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejecting the request (if applicable)', verbose_name='Rejection Reason')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Requested At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='Responded At')),
                ('client', models.ForeignKey(limit_choices_to={'role': 'CLIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_requests_made', to=settings.AUTH_USER_MODEL, verbose_name='Client')),
                ('doctor', models.ForeignKey(blank=True, help_text='Leave blank for specialty-based routing', limit_choices_to={'role': 'DOCTOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_requests_received', to=settings.AUTH_USER_MODEL, verbose_name='Requested Doctor')),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_requests', to='episodes.healthepisode', verbose_name='Health Episode')),
                ('requested_specialty', models.ForeignKey(blank=True, help_text='Optional: specify a specialty for routing', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_requests', to='doctors.specialty', verbose_name='Requested Specialty')),
            ],
            options={
                'verbose_name': 'Doctor Request',
                'verbose_name_plural': 'Doctor Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
