# Generated by Django 5.0.14 on 2026-09-11 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('episodes', '0003_healthepisode_video_started_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthepisode',
            name='title',
            field=models.CharField(blank=True, help_text='A brief description of this health issue', max_length=255, verbose_name='Episode Title'),
        ),
    ]
